### ISSUE TITLE
more model needed

### ISSUE THREAD

**Issue by pengdejia** [awslabs/pptod#8]
can you provide your model in multiwoz2.1 finetune?

**Comment by yxuansu** [comment]
> can you provide your model in multiwoz2.1 finetune?

Hi, thank you for your interest in our work. Due to copyright issue, we are not allowed to release checkpoints on MultiWOZ 2.1 benchmark. However, you can download the data here (https://github.com/TonyNemo/UBAR-MultiWOZ) and pre-process it by yourself. Then, you can use our code to replicate the result.
